/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eg.edu.alexu.csd.oop.calculator.cs73;
import eg.edu.alexu.csd.oop.calculator.Calculator;

/**
 *
 * @author youssefali
 */
public class MainWindow extends javax.swing.JFrame {

    Calculator myCalc;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        myCalc = new CalculatorClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inputScreen = new javax.swing.JTextField();
        resultScreen = new javax.swing.JLabel();
        nineBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        mlpBtn = new javax.swing.JButton();
        divBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        getResultBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        zeroBtn = new javax.swing.JButton();
        resetScreenBtn = new javax.swing.JButton();
        currBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(113, 113, 113));

        jPanel1.setBackground(new java.awt.Color(146, 220, 217));

        jLabel1.setBackground(new java.awt.Color(146, 220, 217));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 101, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Youssef's Calculator");
        jLabel1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        inputScreen.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N

        resultScreen.setBackground(new java.awt.Color(254, 254, 254));
        resultScreen.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        resultScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultScreen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nineBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        nineBtn.setText("9");
        nineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final final java.awt.event.MouseEvent evt) {
                nineBtnMouseClicked(evt);
            }
        });

        sevenBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final final java.awt.event.MouseEvent evt) {
                sevenBtnMouseClicked(evt);
            }
        });

        eightBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        eightBtn.setText("8");
        eightBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final final java.awt.event.MouseEvent evt) {
                eightBtnMouseClicked(evt);
            }
        });

        fourBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        fourBtn.setText("4");
        fourBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                fourBtnMouseClicked(evt);
            }
        });

        fiveBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                fiveBtnMouseClicked(evt);
            }
        });

        sixBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        sixBtn.setText("6");
        sixBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                sixBtnMouseClicked(evt);
            }
        });

        twoBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        twoBtn.setText("2");
        twoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                twoBtnMouseClicked(evt);
            }
        });

        threeBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        threeBtn.setText("3");
        threeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                threeBtnMouseClicked(evt);
            }
        });

        oneBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        oneBtn.setText("1");
        oneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                oneBtnMouseClicked(evt);
            }
        });

        mlpBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        mlpBtn.setText("*");
        mlpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                mlpBtnMouseClicked(evt);
            }
        });

        divBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        divBtn.setText("/");
        divBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                divBtnMouseClicked(evt);
            }
        });

        plusBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        plusBtn.setText("+");
        plusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                plusBtnMouseClicked(evt);
            }
        });

        minusBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        minusBtn.setText("-");
        minusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                minusBtnMouseClicked(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        deleteBtn.setText("Del");
        deleteBtn.setToolTipText("Modulus, the two numbers must be integers.");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        dotBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        dotBtn.setText(".");
        dotBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                dotBtnMouseClicked(evt);
            }
        });

        prevBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        prevBtn.setText("<< Prev");
        prevBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                prevBtnMouseClicked(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        nextBtn.setText("Next >>");
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                nextBtnMouseClicked(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        loadBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        loadBtn.setText("Load");
        loadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                loadBtnMouseClicked(evt);
            }
        });

        getResultBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        getResultBtn.setText("=");
        getResultBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                getResultBtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Made by Youssef Ali, 2017");

        zeroBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                zeroBtnMouseClicked(evt);
            }
        });

        resetScreenBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        resetScreenBtn.setText("AC");
        resetScreenBtn.setToolTipText("Modulus, the two numbers must be integers.");
        resetScreenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                resetScreenBtnMouseClicked(evt);
            }
        });

        currBtn.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        currBtn.setText("Current");
        currBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                currBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputScreen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(currBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(16, 16, 16)
                                            .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(mlpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(16, 16, 16)
                                            .addComponent(divBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(16, 16, 16)
                                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(resetScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(resultScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mlpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(resetScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(getResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    } // </editor-fold>

    private void saveBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        myCalc.save();
    }

    private void loadBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        myCalc.load();
    }

    private void resetScreenBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText("");
    }

    private void deleteBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        String text = inputScreen.getText();
        if (text.equals(""))
            return;
        inputScreen.setText(text.substring(0, text.length() - 1));
    }

    private void mlpBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "*");
    }

    private void divBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "/");
    }

    private void plusBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "+");
    }

    private void minusBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "-");
    }

    private void zeroBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "0");
    }

    private void threeBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "3");
    }

    private void twoBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "2");
    }

    private void fiveBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "5");
    }

    private void oneBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "1");
    }

    private void fourBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "4");
    }

    private void sixBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "6");
    }

    private void sevenBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "7");
    }

    private void eightBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "8");
    }

    private void nineBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + "9");
    }

    private void prevBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(myCalc.prev());
    }

    private void nextBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(myCalc.next());
    }

    private void getResultBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        String operation = inputScreen.getText();
        myCalc.input(operation);
        resultScreen.setText(myCalc.getResult());
        inputScreen.setText("");
    }

    private void dotBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(inputScreen.getText() + ".");
    }

    private void currBtnMouseClicked(final java.awt.event.MouseEvent evt) {
        inputScreen.setText(myCalc.current());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton currBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton divBtn;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton getResultBtn;
    private javax.swing.JTextField inputScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton mlpBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JButton resetScreenBtn;
    private javax.swing.JLabel resultScreen;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration
}